namespace BatteryManagement.Domain;

public sealed class AppUser { public long Id { get; set; } public string Username { get; set; } = ""; public string Role { get; set; } = "Operator"; public bool Active { get; set; } = true; }
public sealed class BatteryModel { public long Id { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string Chemistry { get; set; } = "LFP"; public decimal Voltage { get; set; } public decimal CapacityAh { get; set; } public decimal EnergyWh => Voltage * CapacityAh; public string Configuration { get; set; } = ""; public string BmsSpecification { get; set; } = ""; public string Dimensions { get; set; } = ""; public int WarrantyMonths { get; set; } = 24; public decimal LabourCharges { get; set; } = 1500m; public decimal ElectricityCharges { get; set; } = 500m; public bool Active { get; set; } = true; }
public sealed class ComponentBatch { public long Id { get; set; } public string ComponentName { get; set; } = ""; public string Supplier { get; set; } = ""; public string BatchCode { get; set; } = ""; public decimal Quantity { get; set; } public decimal AvailableQuantity { get; set; } public decimal UnitCost { get; set; } public string Location { get; set; } = "Main Store"; public string Reference { get; set; } = ""; public DateTime ReceivedAt { get; set; } }
public sealed class BatteryPack { public long Id { get; set; } public string SerialNumber { get; set; } = ""; public string QrToken { get; set; } = ""; public string ModelCode { get; set; } = ""; public string ModelName { get; set; } = ""; public string Chemistry { get; set; } = ""; public string SourceBatch { get; set; } = ""; public DateTime ManufacturedAt { get; set; } public string Status { get; set; } = "InProduction"; public decimal MeasuredVoltage { get; set; } public decimal MeasuredCapacityAh { get; set; } public decimal HealthPercent { get; set; } public string BmsSpecification { get; set; } = ""; public string Tester { get; set; } = ""; public string QcNotes { get; set; } = ""; }
public sealed class Customer { public long Id { get; set; } public string Name { get; set; } = ""; public string Phone { get; set; } = ""; public string Address { get; set; } = ""; public string VehicleNumber { get; set; } = ""; }
public sealed class Dealer { public long Id { get; set; } public string Name { get; set; } = ""; public string Phone { get; set; } = ""; public string Address { get; set; } = ""; }
public sealed class Sale { public long Id { get; set; } public string InvoiceNumber { get; set; } = ""; public string PackSerial { get; set; } = ""; public string SaleType { get; set; } = "Retail"; public string PartyName { get; set; } = ""; public decimal Amount { get; set; } public DateTime SoldAt { get; set; } }
public sealed class InvoiceHeader { public long Id { get; set; } public string InvoiceNumber { get; set; } = ""; public string SaleType { get; set; } = "Retail"; public string PartyName { get; set; } = ""; public string FatherName { get; set; } = ""; public string Phone { get; set; } = ""; public string Address { get; set; } = ""; public string VehicleNumber { get; set; } = ""; public decimal TaxableAmount { get; set; } public decimal CgstAmount { get; set; } public decimal SgstAmount { get; set; } public decimal IgstAmount { get; set; } public decimal CessAmount { get; set; } public decimal GrandTotal { get; set; } public decimal PaidAmount { get; set; } public decimal BalanceAmount { get; set; } public DateTime SoldAt { get; set; } public string WarrantyStatus { get; set; } = ""; }
public sealed class SaleItemRow { public long Id { get; set; } public string InvoiceNumber { get; set; } = ""; public string ItemType { get; set; } = "Battery"; public string ItemDescription { get; set; } = ""; public string PackSerial { get; set; } = ""; public string HsnCode { get; set; } = "87116020"; public string ChassisVin { get; set; } = ""; public string EngineMotor { get; set; } = ""; public string Color { get; set; } = ""; public string KeyController { get; set; } = ""; public string WrcNo { get; set; } = ""; public string ChargerInfo { get; set; } = ""; public string BatteryInfo { get; set; } = ""; public decimal Quantity { get; set; } = 1; public decimal UnitPrice { get; set; } public decimal TotalAmount => Quantity * UnitPrice; }
public sealed class PartyLedgerEntry { public long Id { get; set; } public string PartyName { get; set; } = ""; public string PartyType { get; set; } = "Customer"; public DateTime TransactionDate { get; set; } public string Reference { get; set; } = ""; public string Description { get; set; } = ""; public decimal Debit { get; set; } public decimal Credit { get; set; } public decimal Balance { get; set; } }
public sealed class Warranty { public long Id { get; set; } public string PackSerial { get; set; } = ""; public string CustomerName { get; set; } = ""; public DateTime StartDate { get; set; } public DateTime EndDate { get; set; } public string Status { get; set; } = "Active"; }
public sealed class WarrantyClaim { public long Id { get; set; } public string ClaimNumber { get; set; } = ""; public string PackSerial { get; set; } = ""; public string Complaint { get; set; } = ""; public string Status { get; set; } = "Submitted"; public string Resolution { get; set; } = ""; public string ReplacementSerial { get; set; } = ""; public string Notes { get; set; } = ""; public DateTime CreatedAt { get; set; } }
public sealed class StockMovement { public long Id { get; set; } public string MovementType { get; set; } = ""; public string Reference { get; set; } = ""; public string Item { get; set; } = ""; public decimal Quantity { get; set; } public DateTime OccurredAt { get; set; } public string Notes { get; set; } = ""; }
public sealed class ComponentMaster { public long Id { get; set; } public string ComponentCode { get; set; } = ""; public string Name { get; set; } = ""; public string Category { get; set; } = "BMS"; public string Specifications { get; set; } = ""; public decimal UnitPrice { get; set; } public string DefaultSupplier { get; set; } = ""; public bool Active { get; set; } = true; }
public sealed class ModelBomItem { public long Id { get; set; } public string ModelCode { get; set; } = ""; public string ComponentCode { get; set; } = ""; public string ComponentName { get; set; } = ""; public string Category { get; set; } = ""; public decimal Quantity { get; set; } = 1; public decimal UnitPrice { get; set; } public decimal TotalCost => Quantity * UnitPrice; }
